version: '3'
services:
  postgres_db:
    image: postgres:14-alpine
    container_name: "postgres${PORT}"
    environment:
      - "POSTGRES_PASSWORD=${PSQL_PASS}"
      - "POSTGRES_DB=${PSQL_DB}"
      - "POSTGRES_USER=${PSQL_USER}"
    ports:
      - "100${PORT}:55${PORT}"
    volumes:
      - "${POSTGRES_VOLUME_PATH}:/usr/src/postgres"
    command: "-p 55${PORT}"
  mysql_db:
    image: mysql:5.7
    container_name: "mysql${PORT}"
    #restart: always
    environment:
      - "MYSQL_DATABASE=${MYSQL_DB}"
      # So you don't have to use root, but you can if you like
      - "MYSQL_USER=${MYSQL_USER}"
      # You can use whatever password you like
      - "MYSQL_PASSWORD=${MYSQL_DB}"
      # Password for root access
      - "MYSQL_ROOT_PASSWORD=${MYSQL_PASS}"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '110${PORT}:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - '${MYSQL_VOLUME_PATH}:/var/lib/mysql'
